var cookieScripts=document.getElementsByTagName("script"),cookieScriptSrc=cookieScripts[cookieScripts.length-1].src,cookieQuery=null,cookieScriptPosition="bottom",cookieScriptSide="left",cookieScriptSource="cookie-script.com",cookieScriptDomain="",cookieScriptReadMore="http://www.aboutcookies.org/",cookieId="a494d4ab4c882ee266322c697a3de5fb",cookieScriptDebug=0,cookieScriptCurrentUrl=window.location.href,cookieScriptTitle='<h4 id="cookiescript_header">Nous utilisons des Cookies</h4>',cookieScriptDesc=
"Nous utilisons des cookies pour collecter des statistiques anonymes. En poursuivant votre navigation vous acceptez ces cookies.",cookieScriptAccept="\u00d7",cookieScriptMore="En savoir plus",cookieScriptCopyrights="",cookieScriptLoadJavaScript=function(e,d){var c=document.getElementsByTagName("head")[0],a=document.createElement("script");a.type="text/javascript";a.src=e;void 0!=d&&(a.onload=a.onreadystatechange=function(){a.readyState&&!/loaded|complete/.test(a.readyState)||(a.onload=a.onreadystatechange=
null,c&&a.parentNode&&c.removeChild(a),a=void 0,d())});c.insertBefore(a,c.firstChild)},InjectCookieScript=function(){function e(){cookieQuery('iframe[data-cookiescript="accepted"]').not(":has([src])").each(function(){var a=this,a=a.contentWindow?a.contentWindow:a.contentDocument.document?a.contentDocument.document:a.contentDocument;a.document.open();a.document.write(cookieQuery(this).attr("alt"));a.document.close()})}function d(a){"show"==a?(cookieQuery("#cookiescript_overlay",cookieScriptWindow).show(),
cookieQuery("#cookiescript_info_box",cookieScriptWindow).show()):"hide"==a&&(cookieQuery("#cookiescript_overlay",cookieScriptWindow).hide(),cookieQuery("#cookiescript_info_box",cookieScriptWindow).hide())}function c(){cookieQuery('img[data-cookiescript="accepted"]').each(function(){cookieQuery(this).attr("src",cookieQuery(this).attr("data-src"))});cookieQuery('script[type="text/plain"][data-cookiescript="accepted"]').each(function(){cookieQuery(this).attr("src")?cookieQuery(this).after('<script type="text/javascript" src="'+
cookieQuery(this).attr("src")+'">\x3c/script>'):cookieQuery(this).after('<script type="text/javascript">'+cookieQuery(this).html()+"\x3c/script>");cookieQuery(this).empty()});cookieQuery('iframe[data-cookiescript="accepted"]').each(function(){cookieQuery(this).attr("src",cookieQuery(this).attr("data-src"))});cookieQuery('embed[data-cookiescript="accepted"]').each(function(){cookieQuery(this).replaceWith(cookieQuery(this).attr("src",cookieQuery(this).attr("data-src"))[0].outerHTML)});cookieQuery('object[data-cookiescript="accepted"]').each(function(){cookieQuery(this).replaceWith(cookieQuery(this).attr("data",
cookieQuery(this).attr("data-data"))[0].outerHTML)});cookieQuery('link[data-cookiescript="accepted"]').each(function(){cookieQuery(this).attr("href",cookieQuery(this).attr("data-href"))})}cookieScriptDropfromFlag=0;if(cookieScriptSrc!="http://"+cookieScriptSource+"/s/"+cookieId+".js"&&cookieScriptSrc!="http://chs02."+cookieScriptSource+"/s/"+cookieId+".js"&&cookieScriptSrc!="http://chs03."+cookieScriptSource+"/s/"+cookieId+".js"&&cookieScriptSrc!="https://"+cookieScriptSource+"/s/"+cookieId+".js"&&
""!=cookieScriptSrc)return!1;cookieScriptDroptoFlag=0;cookieScriptCreateCookie=function(a,d,b){var c="https:"==window.location.protocol?";secure":"",e="",f;b&&(f=new Date,f.setTime(f.getTime()+864E5*b),e="; expires="+f.toGMTString());b="";""!=cookieScriptDomain&&(b="; domain="+cookieScriptDomain);document.cookie=a+"="+d+e+b+"; path=/"+c};cookieScriptReadCookie=function(a){a+="=";for(var d=document.cookie.split(";"),b,c=0;c<d.length;c++){for(b=d[c];" "==b.charAt(0);)b=b.substring(1,b.length);if(0==
b.indexOf(a))return b.substring(a.length,b.length)}return null};cookieQuery(function(){cookieScriptWindow=window.document;cookieQuery("#cookiescript_injected",cookieScriptWindow).remove();cookieQuery("#cookiescript_overlay",cookieScriptWindow).remove();cookieQuery("#cookiescript_info_box",cookieScriptWindow).remove();cookieScriptCurrentValue=cookieScriptReadCookie("cookiescriptaccept");if("visit"==cookieScriptCurrentValue)return!1;cookieQuery("body",cookieScriptWindow).append('<div id="cookiescript_injected">'+
cookieScriptTitle+cookieScriptDesc+' <span id="cookiescript_readmore">'+cookieScriptMore+'</span><div id="cookiescript_accept">'+cookieScriptAccept+'</div><div style="clear:both"></div><a href="//'+cookieScriptSource+'" target="_blank" id="cookiescript_link" style="display:block !important">Free cookie consent by cookie-script.com</a><div id="cookiescript_pixel"></div>');cookieQuery("#cookiescript_injected",cookieScriptWindow).css({"background-color":"#111111","z-index":999999,opacity:1,position:"fixed",
padding:"15px",width:"300px","font-size":"13px","font-weight":"normal","text-align":"left",color:"#FFFFFF","font-family":"Arial, sans-serif",display:"none","line-height":"15px","letter-spacing":"normal","-moz-box-shadow":"0px 0px 8px #000000","-webkit-box-shadow":"0px 0px 8px #000000","box-shadow":"0px 0px 8px #000000"});"top"==cookieScriptPosition?cookieQuery("#cookiescript_injected",cookieScriptWindow).css("top",0):cookieQuery("#cookiescript_injected",cookieScriptWindow).css("bottom",0);"left"==
cookieScriptSide?cookieQuery("#cookiescript_injected",cookieScriptWindow).css("left",0):cookieQuery("#cookiescript_injected",cookieScriptWindow).css("right",0);cookieQuery("#cookiescript_injected h4#cookiescript_header",cookieScriptWindow).css({"background-color":"#111111","z-index":999999,padding:"0 0 7px 0","text-align":"left",color:"#FFFFFF","font-family":"Arial, sans-serif",display:"block","font-size":"15px","font-weight":"bold","line-height":"normal","letter-spacing":"normal","font-style":"normal",
margin:"0"});cookieQuery("#cookiescript_injected a",cookieScriptWindow).css({"text-decoration":"underline",color:"#FFFFFF"});cookieQuery("#cookiescript_injected a#cookiescript_link",cookieScriptWindow).css({"text-decoration":"none",color:"#FFFFFF","float":"right","font-size":"90%","text-decoration":"none","margin-top":"8px"});cookieQuery("#cookiescript_injected span#cookiescript_readmore",cookieScriptWindow).css({border:0,padding:"0","text-decoration":"underline",cursor:"pointer",margin:"0","white-space":"nowrap"});
cookieQuery("#cookiescript_injected div#cookiescript_accept",cookieScriptWindow).css({"-webkit-border-radius":"10px","-khtml-border-radius":"10px","-moz-border-radius":"10px","border-radius":"10px",border:0,padding:"0",cursor:"pointer",margin:"0","-webkit-transition":"0.25s","-moz-transition":"0.25s",transition:"0.25s",width:"20px",height:"20px",position:"absolute",top:"12px",right:"17px","border-radius":"10px","text-align":"center","font-weight":"bold","line-height":"21px","font-size":"20px"});cookieQuery("#cookiescript_injected div#cookiescript_accept",
cookieScriptWindow).css({"background-color":"#5BB75B",color:"#FFFFFF","float":"left"});cookieQuery("#cookiescript_injected span#cookiescript_readmore",cookieScriptWindow).css({});cookieQuery("#cookiescript_injected div#cookiescript_pixel",cookieScriptWindow).css({width:"1px",height:"1px","float":"left"});cookieQuery("#cookiescript_injected #cookiescript_pixel").css({"background-image":"url(//chs03."+cookieScriptSource+"/pixel.gif?p="+cookieId+"&a=s)"});cookieQuery("#cookiescript_injected",cookieScriptWindow).fadeIn(1E3);
cookieQuery("#cookiescript_injected div#cookiescript_accept",cookieScriptWindow).click(function(){cookieQuery("#cookiescript_injected #cookiescript_pixel").css({"background-image":"url(//chs03."+cookieScriptSource+"/pixel.gif?p="+cookieId+"&a=o)"});"undefined"===typeof cookieScriptScrollfired&&(cookieQuery("#cookiescript_injected",cookieScriptWindow).fadeOut(200),cookieScriptCreateCookie("cookiescriptaccept","visit",30),d("hide"),c())});cookieQuery("#cookiescript_injected span#cookiescript_readmore",
cookieScriptWindow).click(function(){cookieQuery("#cookiescript_injected #cookiescript_pixel").css({"background-image":"url(//chs03."+cookieScriptSource+"/pixel.gif?p="+cookieId+"&a=r)"});window.open(cookieScriptReadMore,"_blank");return!1});cookieQuery("#cookiescript_overlay",cookieScriptWindow).click(function(){d("hide")});cookieQuery("#cookiescript_info_close",cookieScriptWindow).click(function(){d("hide")});document.onkeydown=function(a){a=a||window.event;27==a.keyCode&&d("hide")};e()});"visit"!=
cookieScriptReadCookie("cookiescriptaccept")&&"shown"!=cookieScriptReadCookie("cookiescriptaccept")||c()};
window.jQuery&&jQuery.fn&&/^(1\.[8-9]|2\.[0-9])/.test(jQuery.fn.jquery)?(cookieScriptDebug&&window.console&&console.log("Using existing jQuery version "+jQuery.fn.jquery),cookieQuery=window.jQuery,InjectCookieScript()):(cookieScriptDebug&&window.console&&console.log("Loading jQuery 1.8.1 from ajax.googleapis.com"),cookieScriptLoadJavaScript(("https:"==document.location.protocol?"https://":"http://")+"ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js",function(){cookieQuery=jQuery.noConflict(!0);
InjectCookieScript()}));

